### ISSUE TITLE
Support Poetry's table-format for dependency definition

### ISSUE THREAD

**Issue by NiklasRosenstein** [NiklasRosenstein/slap#52]
Poetry dependencies can be defined like

```toml
[tool.poetry.dependencies]
package1 = "^0.1.0"
package2 = { version = "^0.1.0" }
```

And currently, we only support the first format.

The second format comes with the additional complexity of support different types of dependencies, sources (PyPI indices) and marking dependencies as optional.
